/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export class Constants {
  static readonly FULL_PERCENT = '100%'
  static readonly HALF_PERCENT = '50%'
  static readonly DATA_PANEL_CIRCLE_WIDTH_MD = '90%'
  static readonly DATA_PANEL_CIRCLE_WIDTH_LG = '80%'
  /*
  space
   */
  static readonly SPACE_2 = 2
  static readonly SPACE_8 = 8
  static readonly SPACE_10 = 10
  static readonly SPACE_11 = 11
  static readonly SPACE_12 = 12
  static readonly SPACE_15 = 15
  static readonly SPACE_16 = 16
  static readonly SPACE_24 = 24
  /*
  字体大小
   */
  static readonly FONT_SIZE_TIMER = 60
  static readonly FONT_SIZE_TITLE = 20
  static readonly FONT_SIZE_SUBTITLE = 18
  static readonly FONT_SIZE_NORMAL = 16
  static readonly FONT_SIZE_SMALL = 14
  /*
  行高
   */
  static readonly LINE_HEIGHT_NORMAL = 21
  static readonly LINE_HEIGHT_TITLE = 27
  static readonly LINE_HEIGHT_DIALOG_TITLE = 26
  static readonly LINE_HEIGHT_SUBTITLE = 24
  static readonly LINE_HEIGHT_FONT_SECONDARY = 19
  /*
  边框半径
   */
  static readonly BORDER_RADIUS_NORMAL = 16
  static readonly BORDER_RADIUS_SWITCH = 18
  /*
  尺寸高度
   */
  static readonly SIZE_ICON_BACKWARD = 40
  static readonly HEIGHT_TEXT_TIMER = 200
  static readonly HEIGHT_TITLE = 56
  static readonly HEIGHT_SUBTITLE = 24
  static readonly HEIGHT_BUTTON = 40
  static readonly HEIGHT_RECORD_ITEM = 64
  static readonly HEIGHT_TIMER_SWITCH = 36
  /*
  动画时间
   */
  static readonly ANIMATION_DURATION = 300
  /*
  最大时长
   */
  static readonly MAXIMUM_TIME = 86400
}
