export class SettingsRoutes {
  static readonly RECORD: string = 'RecordSettingsPage';
  static readonly CALENDAR_SYNC: string = 'CalendarSyncSettingsPage';
  static readonly TAG: string = 'TagSettingsPage';
  static readonly IDEA_POOL: string = 'IdeaPoolSettingsPage';
  static readonly REFLECT_CHART: string = 'ReflectChartVisibilitySettingsPage';
  static readonly APPEARANCE: string = 'AppearanceSettingsPage';
  static readonly QUICK_LAUNCH: string = 'EditSwissKnifePage';
  static readonly BACKUP: string = 'BackupSettingsPage';
  static readonly ABOUT: string = 'AboutSettingsPage';
}
